=== champgm/home-dashboard/src/backend/documentation/schemas/group.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "id": "group",
  "properties": {
    "action": {
      "$ref": "state.json#"
    },
    "class": {
      "id": "/properties/class",
      "type": "string"
    },
    "lights": {
      "id": "/properties/lights",
      "items": {
        "id": "/properties/lights/items",
        "type": "string"
      },
      "type": "array"
    },
    "name": {
      "id": "/properties/name",
      "type": "string"
    },
    "state": {
      "id": "/properties/state",
      "properties": {
        "all_on": {
          "id": "/properties/state/properties/all_on",
          "type": "boolean"
        },
        "any_on": {
          "id": "/properties/state/properties/any_on",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "type": {
      "id": "/properties/type",
      "type": "string"
    }
  },
  "type": "object"
}

=== champgm/home-dashboard/src/backend/documentation/examples/group.json
{
  "name": "Den",
  "lights": [
    "6",
    "1",
    "2",
    "3"
  ],
  "type": "Room",
  "state": {
    "all_on": false,
    "any_on": false
  },
  "class": "Living room",
  "action": {
    "on": false,
    "bri": 254,
    "hue": 33946,
    "sat": 5,
    "effect": "none",
    "xy": [
      0.3791,
      0.3759
    ],
    "ct": 248,
    "alert": "none",
    "colormode": "xy"
  }
}
