=== champgm/home-dashboard/src/backend/documentation/schemas/light.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "id": "light",
  "properties": {
    "state": {
      "$ref": "state.json#"
    },
    "manufacturername": {
      "id": "/properties/manufacturername",
      "type": "string"
    },
    "modelid": {
      "id": "/properties/modelid",
      "type": "string"
    },
    "name": {
      "id": "/properties/name",
      "type": "string"
    },
    "swversion": {
      "id": "/properties/swversion",
      "type": "string"
    },
    "type": {
      "id": "/properties/type",
      "type": "string"
    },
    "uniqueid": {
      "id": "/properties/uniqueid",
      "type": "string"
    }
  },
  "type": "object"
}

=== champgm/home-dashboard/src/backend/documentation/examples/light.json
{
  "state": {
    "on": false,
    "bri": 253,
    "hue": 16055,
    "sat": 72,
    "effect": "none",
    "xy": [
      0.4166,
      0.3961
    ],
    "ct": 301,
    "alert": "none",
    "colormode": "xy",
    "reachable": true
  },
  "type": "Extended color light",
  "name": "ColorLamp1",
  "modelid": "LCT007",
  "manufacturername": "Philips",
  "uniqueid": "00:17:88:01:10:5a:d0:e3-0b",
  "swversion": "5.38.1.14919"
}
