=== champgm/home-dashboard/src/backend/documentation/schemas/rule.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "id": "rule",
  "properties": {
    "actions": {
      "id": "/properties/actions",
      "items": {
        "id": "/properties/actions/items",
        "properties": {
          "address": {
            "id": "/properties/actions/items/properties/address",
            "type": "string"
          },
          "body": {
            "id": "/properties/actions/items/properties/body",
            "properties": {
              "scene": {
                "id": "/properties/actions/items/properties/body/properties/scene",
                "type": "string"
              }
            },
            "type": "object"
          },
          "method": {
            "id": "/properties/actions/items/properties/method",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "conditions": {
      "id": "/properties/conditions",
      "items": {
        "id": "/properties/conditions/items",
        "properties": {
          "address": {
            "id": "/properties/conditions/items/properties/address",
            "type": "string"
          },
          "operator": {
            "id": "/properties/conditions/items/properties/operator",
            "type": "string"
          },
          "value": {
            "id": "/properties/conditions/items/properties/value",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "created": {
      "id": "/properties/created",
      "type": "string"
    },
    "lasttriggered": {
      "id": "/properties/lasttriggered",
      "type": "string"
    },
    "name": {
      "id": "/properties/name",
      "type": "string"
    },
    "owner": {
      "id": "/properties/owner",
      "type": "string"
    },
    "recycle": {
      "id": "/properties/recycle",
      "type": "boolean"
    },
    "status": {
      "id": "/properties/status",
      "type": "string"
    },
    "timestriggered": {
      "id": "/properties/timestriggered",
      "type": "integer"
    }
  },
  "type": "object"
}

=== champgm/home-dashboard/src/backend/documentation/examples/rule.json
{
  "name": "Tap 7.4 Default",
  "owner": "1234",
  "created": "2016-11-22T23:01:37",
  "lasttriggered": "none",
  "timestriggered": 0,
  "status": "enabled",
  "recycle": false,
  "conditions": [
    {
      "address": "/sensors/7/state/buttonevent",
      "operator": "eq",
      "value": "18"
    },
    {
      "address": "/sensors/7/state/lastupdated",
      "operator": "dx"
    }
  ],
  "actions": [
    {
      "address": "/groups/0/action",
      "method": "PUT",
      "body": {
        "scene": "8a99c376a-on-0"
      }
    }
  ]
}
