=== champgm/home-dashboard/src/backend/documentation/schemas/schedule.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "id": "schedule",
  "properties": {
    "command": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "definitions": {},
      "id": "command",
      "properties": {
        "address": {
          "id": "/properties/address",
          "type": "string"
        },
        "body": {
          "id": "/properties/body",
          "properties": {
            "scene": {
              "id": "/properties/body/properties/scene",
              "type": "string"
            }
          },
          "type": "object"
        },
        "method": {
          "id": "/properties/method",
          "type": "string"
        }
      },
      "type": "object"
    },
    "created": {
      "id": "/properties/created",
      "type": "string"
    },
    "description": {
      "id": "/properties/description",
      "type": "string"
    },
    "localtime": {
      "id": "/properties/localtime",
      "type": "string"
    },
    "name": {
      "id": "/properties/name",
      "type": "string"
    },
    "recycle": {
      "id": "/properties/recycle",
      "type": "boolean"
    },
    "status": {
      "id": "/properties/status",
      "type": "string"
    },
    "time": {
      "id": "/properties/time",
      "type": "string"
    }
  },
  "type": "object"
}

=== champgm/home-dashboard/src/backend/documentation/examples/schedule.json
{
  "name": "wakeup - bedroom",
  "description": "BR - on",
  "command": {
    "address": "/api/1234/groups/0/action",
    "body": {
      "scene": "808140eef-on-30"
    },
    "method": "PUT"
  },
  "localtime": "W124/T05:30:00",
  "time": "W124/T09:30:00",
  "created": "2015-12-04T12:01:11",
  "status": "disabled",
  "recycle": false
}
