=== champgm/home-dashboard/src/backend/documentation/schemas/sensor.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "id": "http://example.com/example.json",
  "properties": {
    "config": {
      "id": "/properties/config",
      "properties": {
        "battery": {
          "id": "/properties/config/properties/battery",
          "type": "integer"
        },
        "lat": {
          "id": "/properties/config/properties/lat",
          "type": "string"
        },
        "long": {
          "id": "/properties/config/properties/long",
          "type": "string"
        },
        "on": {
          "id": "/properties/config/properties/on",
          "type": "boolean"
        },
        "reachable": {
          "id": "/properties/config/properties/reachable",
          "type": "boolean"
        },
        "sunriseoffset": {
          "id": "/properties/config/properties/sunriseoffset",
          "type": "integer"
        },
        "sunsetoffset": {
          "id": "/properties/config/properties/sunsetoffset",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "manufacturername": {
      "id": "/properties/manufacturername",
      "type": "string"
    },
    "modelid": {
      "id": "/properties/modelid",
      "type": "string"
    },
    "name": {
      "id": "/properties/name",
      "type": "string"
    },
    "recycle": {
      "id": "/properties/recycle",
      "type": "boolean"
    },
    "state": {
      "id": "/properties/state",
      "properties": {
        "buttonevent": {
          "id": "/properties/state/properties/buttonevent",
          "type": "integer"
        },
        "daylight": {
          "id": "/properties/state/properties/daylight",
          "type": "null"
        },
        "lastupdated": {
          "id": "/properties/state/properties/lastupdated",
          "type": "string"
        },
        "status": {
          "id": "/properties/state/properties/status",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "swversion": {
      "id": "/properties/swversion",
      "type": "string"
    },
    "type": {
      "id": "/properties/type",
      "type": "string"
    },
    "uniqueid": {
      "id": "/properties/uniqueid",
      "type": "string"
    }
  },
  "type": "object"
}

=== champgm/home-dashboard/src/backend/documentation/examples/sensorLightState.json
{
  "state": {
    "status": 0,
    "lastupdated": "none"
  },
  "config": {
    "on": true,
    "reachable": true
  },
  "name": "Light status",
  "type": "CLIPGenericStatus",
  "modelid": "Model 2015",
  "manufacturername": "all 4 hue",
  "swversion": "1.0",
  "uniqueid": "PFHS-LIGHT-STATE",
  "recycle": false
}

=== champgm/home-dashboard/src/backend/documentation/examples/sensorDaylight.json
{
  "state": {
    "daylight": null,
    "lastupdated": "none"
  },
  "config": {
    "on": true,
    "long": "none",
    "lat": "none",
    "sunriseoffset": 30,
    "sunsetoffset": -30
  },
  "name": "Daylight",
  "type": "Daylight",
  "modelid": "PHDL00",
  "manufacturername": "Philips",
  "swversion": "1.0"
}

=== champgm/home-dashboard/src/backend/documentation/examples/sensorHardware.json
{
  "state": {
    "buttonevent": 1002,
    "lastupdated": "2017-04-11T02:00:26"
  },
  "config": {
    "on": true,
    "battery": 87,
    "reachable": true
  },
  "name": "Hue dimmer switch 1",
  "type": "ZLLSwitch",
  "modelid": "RWL020",
  "manufacturername": "Philips",
  "swversion": "5.45.1.16265",
  "uniqueid": "1234"
}
